#!/bin/bash
echo "Привет брат"
if [ -z "$1" ]; then
  echo " error please write numbres"
  echo " example: docker run myapp 5 "
  exit 1
fi

if [ "$1" = "--help" ]; then
  echo " used "
  echo " docker run myapp <numbers>"
  exit 0
fi

echo "ти передал число: $1"
if [ "$1" -lt 10 ]; then
  echo "OK"
else
  echo "Слишком большое число"
fi
